# Generated by Django 2.1.5 on 2019-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190127_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_icon',
            field=models.ImageField(default='images/default_head.jpeg', upload_to='images'),
        ),
    ]
